DEFAULT_TEXTS = [
    # System settings. Managed by the admin settings screen.
    ("ukrwerkspot", "settings", "system", 10, "is_open", "Сайт відкритий", "false"),
    ("uhrbv", "settings", "system", 10, "is_open", "Сайт відкритий", "false"),
    # ukrwerkspot · coming soon (live now)
    ("ukrwerkspot", "coming_soon", "uk", 10, "meta_title", "Заголовок вкладки", "Ukrwerkspot — відкриття 1 листопада 2026 року"),
    ("ukrwerkspot", "coming_soon", "uk", 20, "meta_description", "Опис для пошуку", "Ukrwerkspot — платформа для українських ZZP-професіоналів у Нідерландах. Договори на постійній основі та приватні замовлення. Відкриття — 1 листопада 2026 року."),
    ("ukrwerkspot", "coming_soon", "uk", 30, "logo", "Логотип", "Ukrwerkspot"),
    ("ukrwerkspot", "coming_soon", "uk", 40, "domain_label", "Підпис домену", "ukrwerkspot.nl"),
    ("ukrwerkspot", "coming_soon", "uk", 50, "eyebrow", "Надзаголовок", "Для українських фахівців у Нідерландах"),
    ("ukrwerkspot", "coming_soon", "uk", 60, "heading_before", "Заголовок (до акценту)", "Разом ми "),
    ("ukrwerkspot", "coming_soon", "uk", 70, "heading_accent", "Заголовок (акцент)", "сильніші."),
    ("ukrwerkspot", "coming_soon", "uk", 80, "intro_1", "Абзац 1", "Довгоочікуваний проєкт для українських ZZP-професіоналів у Нідерландах."),
    ("ukrwerkspot", "coming_soon", "uk", 90, "intro_2", "Абзац 2", "Тепер кожен український ZZP-професіонал зможе укласти договір на постійній основі, а також скористатися послугою приватних замовлень."),
    ("ukrwerkspot", "coming_soon", "uk", 100, "intro_3", "Абзац 3", "Перший крок до нашого гідного майбутнього 💪!"),
    ("ukrwerkspot", "coming_soon", "uk", 110, "launch_label", "Підпис дати відкриття", "Відкриття — 1 листопада 2026 року"),
    ("ukrwerkspot", "coming_soon", "uk", 120, "launch_date_iso", "Дата відкриття (YYYY-MM-DD)", "2026-11-01"),
    ("ukrwerkspot", "coming_soon", "uk", 130, "pill", "Статус на сторінці", "Сайт у розробці"),
    ("ukrwerkspot", "coming_soon", "uk", 140, "art_caption", "Підпис ілюстрації", "Разом будуємо майбутнє"),
    ("ukrwerkspot", "coming_soon", "uk", 150, "footer_note", "Текст у футері", "Незабаром відкриття"),
    # ukrwerkspot · home (after launch)
    ("ukrwerkspot", "home", "uk", 10, "hero_eyebrow", "Hero: надзаголовок", "Українська майстерність. Нідерландські можливості."),
    ("ukrwerkspot", "home", "uk", 20, "hero_title_1", "Hero: рядок 1", "Ваша майстерність."),
    ("ukrwerkspot", "home", "uk", 30, "hero_title_2", "Hero: рядок 2", "Наші можливості."),
    ("ukrwerkspot", "home", "uk", 40, "hero_title_3", "Hero: акцент", "Спільне майбутнє."),
    ("ukrwerkspot", "home", "uk", 50, "hero_text", "Hero: опис", "Працюєте у будівельній сфері в Нідерландах? Приєднуйтесь до бази перевірених майстрів. Заповніть профіль та отримуйте пропозиції через нашого менеджера."),
    ("ukrwerkspot", "home", "uk", 60, "cta_register", "Кнопка анкети", "Заповнити анкету ↗"),
    ("ukrwerkspot", "home", "uk", 70, "cta_how", "Кнопка «як це працює»", "Як це працює"),
    ("ukrwerkspot", "home", "uk", 80, "trust_1", "Довіра 1", "Перевірка VCA"),
    ("ukrwerkspot", "home", "uk", 90, "trust_2", "Довіра 2", "Особистий менеджер"),
    ("ukrwerkspot", "home", "uk", 100, "strip_1", "Стрічка 1", "Майстерність без кордонів"),
    ("ukrwerkspot", "home", "uk", 110, "strip_2", "Стрічка 2", "KVK · VCA · Підтримка українською"),
    ("ukrwerkspot", "home", "uk", 120, "benefits_eyebrow", "Переваги: надзаголовок", "Спокій та впевненість"),
    ("ukrwerkspot", "home", "uk", 130, "benefits_title", "Переваги: заголовок", "Ви працюєте. Ми підтримуємо."),
    ("ukrwerkspot", "home", "uk", 140, "benefits_lead", "Переваги: підзаголовок", "Більше часу для того, що ви вмієте найкраще."),
    ("ukrwerkspot", "home", "uk", 150, "benefit_1_title", "Перевага 1", "Перевірені замовники"),
    ("ukrwerkspot", "home", "uk", 160, "benefit_1_text", "Перевага 1: текст", "Ми перевіряємо компанії перед співпрацею."),
    ("ukrwerkspot", "home", "uk", 170, "benefit_2_title", "Перевага 2", "Захист особистих контактів"),
    ("ukrwerkspot", "home", "uk", 180, "benefit_2_text", "Перевага 2: текст", "Контакти доступні лише вашому менеджеру."),
    ("ukrwerkspot", "home", "uk", 190, "benefit_3_title", "Перевага 3", "Пропозиції за спеціалізацією"),
    ("ukrwerkspot", "home", "uk", 200, "benefit_3_text", "Перевага 3: текст", "Ваш досвід допомагає знайти відповідний проєкт."),
    ("ukrwerkspot", "home", "uk", 210, "benefit_4_title", "Перевага 4", "Підтримка менеджера"),
    ("ukrwerkspot", "home", "uk", 220, "benefit_4_text", "Перевага 4: текст", "Поруч на кожному етапі співпраці."),
    ("ukrwerkspot", "home", "uk", 230, "benefit_5_title", "Перевага 5", "Ваш досвід має значення"),
    ("ukrwerkspot", "home", "uk", 240, "benefit_5_text", "Перевага 5: текст", "Покажіть сертифікати та приклади робіт."),
    ("ukrwerkspot", "home", "uk", 250, "benefit_6_title", "Перевага 6", "Без відкритої публікації даних"),
    ("ukrwerkspot", "home", "uk", 260, "benefit_6_text", "Перевага 6: текст", "У каталозі — лише професійна інформація."),
    ("ukrwerkspot", "home", "uk", 270, "how_eyebrow", "Кроки: надзаголовок", "Лише кілька простих кроків"),
    ("ukrwerkspot", "home", "uk", 280, "how_title", "Кроки: заголовок", "Від анкети до нового проєкту."),
    ("ukrwerkspot", "home", "uk", 290, "step_1", "Крок 1", "Заповніть анкету"),
    ("ukrwerkspot", "home", "uk", 300, "step_2", "Крок 2", "Додайте документи та роботи"),
    ("ukrwerkspot", "home", "uk", 310, "step_3", "Крок 3", "Ми перевіримо ваш профіль"),
    ("ukrwerkspot", "home", "uk", 320, "step_4", "Крок 4", "Отримуйте пропозиції"),
    ("ukrwerkspot", "home", "uk", 330, "step_note", "Примітка до кроків", "Ваші особисті контакти не публікуються. Спілкування із замовниками відбувається через менеджера."),
    ("ukrwerkspot", "home", "uk", 340, "callout_title", "Заклик: заголовок", "Зробіть наступний крок."),
    ("ukrwerkspot", "home", "uk", 350, "callout_text", "Заклик: текст", "Розкажіть про свій досвід — ми допоможемо знайти можливості."),
    ("ukrwerkspot", "home", "uk", 360, "nav_how", "Меню: як це працює", "Як це працює"),
    ("ukrwerkspot", "home", "uk", 370, "nav_benefits", "Меню: для майстрів", "Для майстрів"),
    ("ukrwerkspot", "home", "uk", 380, "nav_faq", "Меню: FAQ", "Поширені запитання"),
    # ukrwerkspot · faq
    ("ukrwerkspot", "faq", "uk", 10, "q1", "Питання 1", "Хто може зареєструватися?"),
    ("ukrwerkspot", "faq", "uk", 20, "a1", "Відповідь 1", "Українські майстри та невеликі будівельні компанії, що працюють у Нідерландах."),
    ("ukrwerkspot", "faq", "uk", 30, "q2", "Питання 2", "Чи потрібна реєстрація KVK?"),
    ("ukrwerkspot", "faq", "uk", 40, "a2", "Відповідь 2", "В анкеті передбачено перевірку KVK менеджером."),
    ("ukrwerkspot", "faq", "uk", 50, "q3", "Питання 3", "Чи обов’язковий VCA?"),
    ("ukrwerkspot", "faq", "uk", 60, "a3", "Відповідь 3", "Так, анкета містить обов’язкове завантаження VCA."),
    ("ukrwerkspot", "faq", "uk", 70, "q4", "Питання 4", "Хто побачить мої особисті дані?"),
    ("ukrwerkspot", "faq", "uk", 80, "a4", "Відповідь 4", "Менеджер бачить повну анкету. Компаніям доступний лише обезличений профіль."),
    ("ukrwerkspot", "faq", "uk", 90, "q5", "Питання 5", "Як я отримуватиму пропозиції?"),
    ("ukrwerkspot", "faq", "uk", 100, "a5", "Відповідь 5", "Усі пропозиції та узгодження проходять через менеджера."),
    ("ukrwerkspot", "faq", "uk", 110, "q6", "Питання 6", "Чи потрібно оплачувати реєстрацію?"),
    ("ukrwerkspot", "faq", "uk", 120, "a6", "Відповідь 6", "Умови реєстрації будуть визначені перед запуском."),
    # uhrbv · coming soon (live now)
    ("uhrbv", "coming_soon", "nl", 10, "meta_title", "Заголовок вкладки", "Opening op 1 november 2026 | UHR BV"),
    ("uhrbv", "coming_soon", "nl", 20, "meta_description", "Опис для пошуку", "UHR BV — Ukrainian Human Resources. Onze website opent op 1 november 2026. Neem nu al contact op voor personeel in de bouwsector in Nederland."),
    ("uhrbv", "coming_soon", "nl", 30, "logo", "Логотип", "UHR BV"),
    ("uhrbv", "coming_soon", "nl", 40, "contact_label", "Посилання «зв’язатися»", "Neem contact op ↗"),
    ("uhrbv", "coming_soon", "nl", 50, "email", "Email", "alexzhuravkevich.group@gmail.com"),
    ("uhrbv", "coming_soon", "nl", 60, "phone", "Телефон", "+31625366263"),
    ("uhrbv", "coming_soon", "nl", 70, "eyebrow", "Надзаголовок", "Ukrainian Human Resources · Nederland"),
    ("uhrbv", "coming_soon", "nl", 80, "heading_before", "Заголовок (до акценту)", "Binnenkort "),
    ("uhrbv", "coming_soon", "nl", 90, "heading_accent", "Заголовок (акцент)", "online."),
    ("uhrbv", "coming_soon", "nl", 100, "lead", "Опис", "Wij zorgen ervoor dat Nederlandse bouwbedrijven op bouwplaatsen door heel Nederland kunnen rekenen op voldoende personeel. Met ons bouwt u meer!"),
    ("uhrbv", "coming_soon", "nl", 110, "launch_label", "Підпис дати відкриття", "Opening op 1 november 2026"),
    ("uhrbv", "coming_soon", "nl", 120, "launch_date_iso", "Дата відкриття (YYYY-MM-DD)", "2026-11-01"),
    ("uhrbv", "coming_soon", "nl", 130, "cta_email", "Кнопка email", "Stuur ons een e-mail"),
    ("uhrbv", "coming_soon", "nl", 140, "cta_phone", "Кнопка телефону", "Bel 06 253 662 63"),
    ("uhrbv", "coming_soon", "nl", 150, "panel_title", "Панель: назва", "UHR BV"),
    ("uhrbv", "coming_soon", "nl", 160, "panel_subtitle", "Панель: підзаголовок", "Ukrainian Human Resources"),
    ("uhrbv", "coming_soon", "nl", 170, "panel_note", "Підпис панелі", "Samen aan het werk"),
    ("uhrbv", "coming_soon", "nl", 180, "address", "Адреса", "Langendijk 1h · 4201 CE Gorinchem"),
    ("uhrbv", "coming_soon", "nl", 190, "footer_badge", "Бейдж у футері", "VCA"),
    # uhrbv · home (ready for later)
    ("uhrbv", "home", "nl", 10, "hero_eyebrow", "Hero: eyebrow", "Ukrainian expertise. Dutch ambition."),
    ("uhrbv", "home", "nl", 20, "hero_title_1", "Hero: regel 1", "Goede mensen."),
    ("uhrbv", "home", "nl", 30, "hero_title_2", "Hero: regel 2", "Sterke projecten."),
    ("uhrbv", "home", "nl", 40, "hero_title_3", "Hero: accent", "Samen bouwen."),
    ("uhrbv", "home", "nl", 50, "hero_text", "Hero: tekst", "Gekwalificeerde vakmensen voor de Nederlandse bouwsector. Wij verbinden uw bouwbedrijf met betrouwbare Oekraïense professionals. Met ons bouwt u meer."),
    ("uhrbv", "home", "nl", 60, "cta_catalog", "Knop catalogus", "Bekijk beschikbare vakmensen ↗"),
    ("uhrbv", "home", "nl", 70, "cta_register", "Knop aanmelden", "Bedrijf aanmelden"),
]

PAGES = {
    "ukrwerkspot": [
        ("coming_soon", "Сторінка очікування"),
        ("home", "Головна після відкриття"),
        ("faq", "Поширені запитання"),
    ],
    "uhrbv": [
        ("coming_soon", "Сторінка очікування"),
        ("home", "Головна після відкриття"),
    ],
}

SITES = [
    ("ukrwerkspot", "Ukrwerkspot"),
    ("uhrbv", "UHR"),
]
